language: ar

pipeline:
  - name: CountVectorsFeaturizer
  
  - name: EmbeddingIntentClassifier
    intent_split_symbol: +
    intent_tokenization_flag: true
  
  
policies:
  - name: KerasPolicy
    batch_size: 50
    epochs: 200
    max_training_samples: 300

  - name: FallbackPolicy
    fallback_action_name: action_default_fallback
  
  - name: MemoizationPolicy
    max_history: 5
  
  - name: FormPolicy
  
  - name: MappingPolicy
